# Generated by Django 5.1 on 2024-09-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('screen_diagonal', models.FloatField()),
                ('display_resolution', models.CharField(max_length=255)),
                ('type_of_matrix', models.CharField(max_length=255)),
                ('screen_refresh_rate', models.PositiveIntegerField()),
                ('count_of_sim_cards', models.PositiveSmallIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('built_in_memory', models.IntegerField()),
                ('operating_system', models.CharField(max_length=255)),
                ('count_of_cores', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('depth', models.CharField(max_length=255)),
                ('guarantee', models.IntegerField()),
                ('country_of_manufacture', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефони',
            },
        ),
    ]
